name: Healthz CI
on:
  pull_request:

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set .env file
        run: |
          touch .env
          echo DB_PASSWORD=root1234 >> .env
          echo DB_NAME=csye6225_db >> .env
          echo DB_USER=root >> .env
          echo DB_PORT=3306 >> .env
          echo DB_HOST=localhost >> .env

      - name: Set up MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install mariadb-server -y
          sudo systemctl start mariadb
          sudo mysql -e "GRANT ALL ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root1234';"

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
