name: packer validate

on:
  [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Building webapp application artifact 
        if: success()
        run: zip -r webapp.zip .

      - name: Initialize packer configuration
        run: packer init webapp.pkr.hcl

      - name: Format template
        id: fmt
        run: |
          set -e
          if ! packer fmt webapp.pkr.hcl; then
            echo "Template is not formatted correctly. Please run 'packer fmt' locally and push the changes."
            exit 1
          fi
          
      - name: Validate Packer
        run: packer validate webapp.pkr.hcl
        env:
          PKR_VAR_database_pass: ${{secrets.DB_PASSWORD}} 
          PKR_VAR_database_user: ${{secrets.DB_USER}}
          PKR_VAR_database_host: ${{secrets.DB_HOST}} 
          PKR_VAR_aws_region: "${{secrets.AWS_REGION}}"
          PKR_VAR_source_ami: "${{secrets.SOURCE_AMI}}"
          PKR_VAR_subnet_id: "${{secrets.SUBNET_ID}}"